/**
 * Generates the tiny JS loader that ships next to compiled .wasm output.
 *
 * This is the only JavaScript yarescript ever produces. It holds no
 * application logic, no transpiled statements, and nothing that grows
 * with your program. It just:
 *   1. fetches/reads the .wasm binary
 *   2. hands it a couple of host functions (console.log, etc.)
 *   3. instantiates it and calls `main`
 *
 * Everything else, meaning your actual program, is compiled
 * WebAssembly bytecode.
 */

export function generateLoaderJs(opts: {
  wasmFileName: string;
  exportedFunctions: string[];
  usedHostFunctions: string[];
}): string {
  const hostFnImpls: Record<string, string> = {
    console_log_string: `
  console_log_string(ptr) {
    const bytes = new Uint8Array(memory.buffer, ptr + 4, new Uint32Array(memory.buffer, ptr, 1)[0]);
    console.log(new TextDecoder("utf-8").decode(bytes));
  },`,
    console_log_int: `
  console_log_int(v) { console.log(v); },`,
    console_log_long: `
  console_log_long(v) { console.log(v); },`,
    console_log_float: `
  console_log_float(v) { console.log(v); },`,
    console_log_double: `
  console_log_double(v) { console.log(v); },`,
    console_log_bool: `
  console_log_bool(v) { console.log(Boolean(v)); },`,
  };

  const imports = opts.usedHostFunctions.map((name) => hostFnImpls[name] ?? `\n  ${name}() { throw new Error("host function '${name}' has no runtime implementation"); },`).join("");

  return `// Auto-generated by the yarescript compiler. Do not edit by hand.
// This file holds no application logic. It only loads and wires up the
// compiled WebAssembly module. Your program's behavior lives in
// ${opts.wasmFileName}.
"use strict";

const fs = require("fs");
const path = require("path");

async function loadYarescriptModule() {
  const wasmPath = path.join(__dirname, ${JSON.stringify(opts.wasmFileName)});
  const bytes = fs.readFileSync(wasmPath);

  let memory; // populated once the module is instantiated; host fns close over it
  const env = {${imports}
  };

  const { instance } = await WebAssembly.instantiate(bytes, { env });
  memory = instance.exports.memory;
  return instance.exports;
}

module.exports = { loadYarescriptModule };

// Allow \`node .yarescript/loader.js\` to just run the program directly.
if (require.main === module) {
  loadYarescriptModule().then((exports) => {
    if (typeof exports.main === "function") {
      exports.main();
    }
  }).catch((err) => {
    console.error("yarescript runtime error:", err);
    process.exitCode = 1;
  });
}
`;
}

export function generateBrowserLoaderJs(opts: {
  wasmFileName: string;
  usedHostFunctions: string[];
}): string {
  const hostFnImpls: Record<string, string> = {
    console_log_string: `
    console_log_string(ptr) {
      const view = new DataView(memory.buffer);
      const len = view.getUint32(ptr, true);
      const bytes = new Uint8Array(memory.buffer, ptr + 4, len);
      console.log(new TextDecoder("utf-8").decode(bytes));
    },`,
    console_log_int: `
    console_log_int(v) { console.log(v); },`,
    console_log_long: `
    console_log_long(v) { console.log(v); },`,
    console_log_float: `
    console_log_float(v) { console.log(v); },`,
    console_log_double: `
    console_log_double(v) { console.log(v); },`,
    console_log_bool: `
    console_log_bool(v) { console.log(Boolean(v)); },`,
  };
  const imports = opts.usedHostFunctions.map((name) => hostFnImpls[name] ?? `\n    ${name}() { throw new Error("host function '${name}' has no runtime implementation"); },`).join("");

  return `// Auto-generated by the yarescript compiler. Do not edit by hand.
// No application logic here, just a loader for ${opts.wasmFileName}.
export async function loadYarescriptModule() {
  const response = await fetch(new URL(${JSON.stringify(opts.wasmFileName)}, import.meta.url));
  const bytes = await response.arrayBuffer();

  let memory;
  const env = {${imports}
  };

  const { instance } = await WebAssembly.instantiate(bytes, { env });
  memory = instance.exports.memory;
  return instance.exports;
}
`;
}
