// Auto-generated by the yarescript compiler. Do not edit by hand.
// No application logic here, just a loader for hello-world.wasm.
export async function loadYarescriptModule() {
  const response = await fetch(new URL("hello-world.wasm", import.meta.url));
  const bytes = await response.arrayBuffer();

  let memory;
  const env = {
    console_log_string(ptr) {
      const view = new DataView(memory.buffer);
      const len = view.getUint32(ptr, true);
      const bytes = new Uint8Array(memory.buffer, ptr + 4, len);
      console.log(new TextDecoder("utf-8").decode(bytes));
    },
  };

  const { instance } = await WebAssembly.instantiate(bytes, { env });
  memory = instance.exports.memory;
  return instance.exports;
}
