// Auto-generated by the yarescript compiler. Do not edit by hand.
// This file holds no application logic. It only loads and wires up the
// compiled WebAssembly module. Your program's behavior lives in
// kitchen-sink.wasm.
"use strict";

const fs = require("fs");
const path = require("path");

async function loadYarescriptModule() {
  const wasmPath = path.join(__dirname, "kitchen-sink.wasm");
  const bytes = fs.readFileSync(wasmPath);

  let memory; // populated once the module is instantiated; host fns close over it
  const env = {
  console_log_string(ptr) {
    const bytes = new Uint8Array(memory.buffer, ptr + 4, new Uint32Array(memory.buffer, ptr, 1)[0]);
    console.log(new TextDecoder("utf-8").decode(bytes));
  },
  console_log_int(v) { console.log(v); },
  console_log_bool(v) { console.log(Boolean(v)); },
  console_log_double(v) { console.log(v); },
  };

  const { instance } = await WebAssembly.instantiate(bytes, { env });
  memory = instance.exports.memory;
  return instance.exports;
}

module.exports = { loadYarescriptModule };

// Allow `node .yarescript/loader.js` to just run the program directly.
if (require.main === module) {
  loadYarescriptModule().then((exports) => {
    if (typeof exports.main === "function") {
      exports.main();
    }
  }).catch((err) => {
    console.error("yarescript runtime error:", err);
    process.exitCode = 1;
  });
}
